### ISSUE TITLE
Potentially good things to add (getSeasons and getPlayerSeasonInfo)

### ISSUE THREAD

**Issue by Nikedi** [xF4b3r/pubgAPI#1]
So i wrote two new things that weren't in the code before and they are getSeasons() and getPlayerSeasonInfo() and they get all the available seasons and info about a player in a season. Here they are: 
```javascript
        static getSeasons(region, callback) {
            this.api_call(`https://api.playbattlegrounds.com/shards/${region}/seasons`).then((response) => {
                callback(response);
            });
        }
```
And
```javascript
        static getPlayerSeasonInfo(id, seasonId, region, callback) {
            this.api_call(`https://api.playbattlegrounds.com/shards/${region}/players/${id}/seasons/${seasonId}`).then((response) => {
                callback(response);
            });
        }
```

**Comment by xF4b3r** [comment]
I added the two functions, thanks Nikedi!

**Comment by Nikedi** [comment]
No Problem and thanks for inviting me to be a contributor.

    perjantaina 25. toukokuuta 2018 klo 7.45.39 UTC+2 Faber <notifications@github.com> kirjoitti:  
 
 
I added the two functions, thanks Nikedi!
